---
title: Analysis of experimental data
subtitle: "{{< var workshop-title >}}"
format:
  anu-light-revealjs:
    width: 1920
    height: 1080
    auto-stretch: false
    html-math-method: katex
    self-contained: false
    css: 
     - /assets/slides.css
    footer: "{{< var workshop-url >}}"
author: Emi Tanaka
institute: Biological Data Science Institute
date-talk: "20th September 2024"
filters:
  - webr
execute: 
  echo: true
webr: 
  show-startup-message: false  
  packages: 
    - tidyverse
    - agridat
---


## {{< fa crosshairs >}} Current learning objective

```{r, include = FALSE}
library(tidyverse)
source("setup.R")
```


```{r}
#| results: asis 
#| echo: false
learning_objectives(4:5)
```


## Simulate the experiment


## Statistical analysis plan

::: f2

**Analysis of variance**

```{r}
#| eval: false
options(knitr.kable.NA = '')
anova(lm(Weight ~ Treatment + Glasshouse, data = df10v4)) |> 
  knitr::kable(digits = 3)
```

**Estimated regression parameters**

```{r}
#| eval: false
summary(lm(Weight ~ Treatment + Glasshouse, data = df10v4)) |> 
  broom::tidy() |> 
  mutate(Term = c("Intercept", "Treatment", "Glasshouse")) |> 
  select(Term, Estimate = estimate, `Std Error` = std.error, `P value` = p.value) |> 
  knitr::kable(digits = 3)
```

:::

## Analysis of variance (ANOVA)


## Linear models 

- ANOVA is a special case of linear models

## Common diagnostics 

- Check the residual plot 
- Outliers 
- Transformation of data
- Multiple comparisons 

## Summary 

